### ISSUE TITLE
Pokpong | Prepare video clip

### ISSUE THREAD

**Issue by GrapesGoober** [GrapesGoober/TodoCards-Project#67]
### Deadline Nov 23
# Problem
Totally forgot that we have to do video clip submission for pokpong.
# To do
- [x] Title, abstract (just like proposal)
- [x] Introduction (just like proposal)
- [x] ER, Context, Dataflow (just like proposal)
- [x] DBMS Implementation
- [ ] Explaination of stored procedures
- [x] Conclusion
# Curious
How should this be done? I'm thinking
- Grapes: Documentation & implementation
- Nanoni: Stored procedures refactoring
- Awocado: Video clip of app demonstration

**Comment by GrapesGoober** [comment]
# Task Allocation
- Show backend implementation
	- [x] Framework (G)
	- [x] API (G)
	- [x] Backend code implementation (Pn)
- (PW) Frontend Demonstration (just a "how to use the app")
- (PW) Conclusion
- Combine all into a document / folder, for submission (PW)
